volumes:
  db-data:


services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      /bin/sh -c
        'python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000'
  
  redis:
    image: redis:5
    ports:
      - "6379:6379"
